### ISSUE TITLE
Allow non-safe images

### ISSUE THREAD

**Issue by samip5** [bakape/captchouli#35]
What is wrong when I try to use tag `kissxsis` and it does this indefinitely and I want to be able to use non-work safe images too?

```
2019/12/27 07:06:58 captchouli: initializing tag=kissxsis explicitness=[safe, questionable, explicit]
fetch attempt: 3290540
```

**Comment by bakape** [comment]
Probably because there are very few images that match this filter:
https://gelbooru.com/index.php?page=post&s=list&tags=kissxsis+solo+-photo+-monochrome+-multiple_girls+-couple+-multiple_boys+-cosplay+-objectification
That's only 2 pages of results. it is entirely possible that the face
detection NN blacklisted almost all of them.

**Comment by bakape** [comment]
Yes, when you also filter out the untagged images with multiple faces and
GIFs/WebM, there are very few images left to work with.
